version: "3.8"
services:
  employee:
    build:
      context: .
    image: employee
    container_name: employee
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb:3306/bootdb
    volumes:
      - ./:/app
    networks:
      - mysql_net
    depends_on:
      - mysqldb
    restart: always
 
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - mysql_net

volumes:
  mysql_data:
    name: mysql_data
  mysql_config:
    name: mysql_config
networks:
  mysql_net:
    name: mysql_net